import { Link } from 'react-router-dom';

interface HomePageProps {
  language: 'ko' | 'en';
}

export function HomePage({ language }: HomePageProps) {
  const content = {
    ko: {
      title: 'Limepie Bootstrap 5 폼 데모',
      subtitle: 'React 폼 빌더로 생성된 Bootstrap 5 스타일 폼',
      features: 'Bootstrap 5 기능',
      featuresList: [
        '반응형 Bootstrap 5 폼 컨트롤',
        'form-control, form-label 등 표준 클래스 사용',
        'Limepie PHP 폼과 동일한 스타일 출력',
        '실시간 유효성 검사',
        '다국어 지원 (한국어/영어)',
        'YAML 스펙 기반 폼 생성',
      ],
      demos: '데모 폼',
      contact: {
        title: '문의 폼',
        desc: '기본 Bootstrap 5 폼 필드와 유효성 검사',
      },
      registration: {
        title: '회원가입 폼',
        desc: '그룹화된 필드와 복잡한 유효성 검사',
      },
      product: {
        title: '상품 폼',
        desc: '다중 입력과 동적 필드',
      },
      compare: {
        title: 'Limepie 비교',
        desc: 'React 폼과 원본 Limepie 폼 비교',
      },
    },
    en: {
      title: 'Limepie Bootstrap 5 Form Demo',
      subtitle: 'Bootstrap 5 styled forms generated by React Form Builder',
      features: 'Bootstrap 5 Features',
      featuresList: [
        'Responsive Bootstrap 5 form controls',
        'Standard classes: form-control, form-label, etc.',
        'Identical styling to Limepie PHP forms',
        'Real-time validation',
        'Multi-language support (Korean/English)',
        'YAML spec-based form generation',
      ],
      demos: 'Demo Forms',
      contact: {
        title: 'Contact Form',
        desc: 'Basic Bootstrap 5 form fields with validation',
      },
      registration: {
        title: 'Registration Form',
        desc: 'Grouped fields with complex validation',
      },
      product: {
        title: 'Product Form',
        desc: 'Multiple inputs and dynamic fields',
      },
      compare: {
        title: 'Limepie Compare',
        desc: 'Compare React form with original Limepie form',
      },
    },
  };

  const t = content[language];

  return (
    <div className="home-page">
      {/* Hero Section */}
      <div className="text-center py-5">
        <h1 className="display-5 fw-bold text-primary">{t.title}</h1>
        <p className="lead text-muted">{t.subtitle}</p>
      </div>

      {/* Features Section */}
      <section className="mb-5">
        <h2 className="h4 mb-4">{t.features}</h2>
        <div className="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3">
          {t.featuresList.map((feature, index) => (
            <div key={index} className="col">
              <div className="d-flex align-items-center p-3 bg-white border rounded">
                <span className="text-success me-2 fw-bold">&#10003;</span>
                <span>{feature}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Demos Section */}
      <section className="mb-5">
        <h2 className="h4 mb-4">{t.demos}</h2>
        <div className="row row-cols-1 row-cols-md-2 g-4">
          <div className="col">
            <Link to="/contact" className="text-decoration-none">
              <div className="card demo-card h-100">
                <div className="card-body">
                  <h5 className="card-title text-primary">{t.contact.title}</h5>
                  <p className="card-text text-muted">{t.contact.desc}</p>
                </div>
              </div>
            </Link>
          </div>
          <div className="col">
            <Link to="/registration" className="text-decoration-none">
              <div className="card demo-card h-100">
                <div className="card-body">
                  <h5 className="card-title text-primary">{t.registration.title}</h5>
                  <p className="card-text text-muted">{t.registration.desc}</p>
                </div>
              </div>
            </Link>
          </div>
          <div className="col">
            <Link to="/product" className="text-decoration-none">
              <div className="card demo-card h-100">
                <div className="card-body">
                  <h5 className="card-title text-primary">{t.product.title}</h5>
                  <p className="card-text text-muted">{t.product.desc}</p>
                </div>
              </div>
            </Link>
          </div>
          <div className="col">
            <Link to="/compare" className="text-decoration-none">
              <div className="card demo-card h-100">
                <div className="card-body">
                  <h5 className="card-title text-primary">{t.compare.title}</h5>
                  <p className="card-text text-muted">{t.compare.desc}</p>
                </div>
              </div>
            </Link>
          </div>
        </div>
      </section>

      {/* Usage Section */}
      <section className="mb-5">
        <h2 className="h4 mb-4">Usage</h2>
        <div className="bg-dark text-light p-4 rounded">
          <pre className="mb-0" style={{ whiteSpace: 'pre-wrap' }}>
{`import { FormBuilder } from '@limepie/form-react';
import contactSpec from './specs/contact.yaml?raw';

// Bootstrap 5 classes are automatically applied:
// - form-label
// - form-control
// - form-select
// - form-check, form-check-input, form-check-label
// - btn, btn-primary, btn-secondary
// - is-invalid, invalid-feedback

<FormBuilder
  spec={contactSpec}
  data={formData}
  language="ko"
  onSubmit={handleSubmit}
  onChange={handleChange}
  className="bootstrap-form"
/>`}
          </pre>
        </div>
      </section>
    </div>
  );
}
